# î‚  î‚¡ î‚¢ î‚£ î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ’ îƒ”

format = """
[ ](bg:#585858)\
$os\
$battery(bg:#CCCC11 fg:#1111CC)\
$username\
[î‚¼](bg:#444444 fg:#585858)\
$hostname\
[î‚¼](bg:#0087AF fg:#444444)\
$directory\
[î‚¼](fg:#0087AF) \
$fill\
$git_branch\
$git_status\
$git_commit\
$nodejs\
$rust\
$localip
$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

[battery]
full_symbol='ó°¹'
empty_symbol='ï‰„'
charging_symbol='ó°‚„'
discharging_symbol='ó°‚€'
unknown_symbol='ó°‚‘'
format = '[$symbol$percentage](red) '


[character]
success_symbol = '[>>>](bold green) '
error_symbol = '[âœ—](bold red) '


# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#585858"
style_root = "bg:#585858"
format = '[$user ]($style)'
disabled = false


# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#585858"
disabled = true # Disabled by default

[fill]
symbol = " "

[hostname]
ssh_only = true
style = "bg:#444444"
ssh_symbol = 'î€Š'
format = '[$ssh_symbol]($style)[ on ]($style)[$hostname](fg:red bg:$style)'

[directory]
style = "fg:#303030 bg:#0087AF"
read_only = 'î‚¢'
read_only_style="fg:#AF0000 bg:#0087AF"
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 5
truncation_symbol = "îœ‚:"
truncate_to_repo = true
home_symbol = 'ó°‹œ'
use_os_path_sep = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ï…œ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "


[c]
symbol = "î˜ "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'
[git_branch]
symbol = "ï˜"
style = "fg:#303030 bg:#CF9562"
format = '[î‚²](fg:#CF9562)[ $symbol $branch ]($style)'

[git_status]
style = "bg:#CF9562 fg:#444444"
conflicted = 'ó°‡=\($count\)'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦=\($count\)'
modified = 'ğŸ“'
staged = '[s=\($count\)](bg:#CF9562 fg:#444444)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
format = '[$all_status$ahead_behind ]($style)[î‚²](bg:#CF9562 fg:#303030 fg:#444444)'

[git_commit]
style = "bg: #CF9562"
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[localip]
style = "bg:#CF9562 fg:#444444"
ssh_only = false
format = '[$localipv4]($style) '
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = "bg:#CF9562 fg:#444444"

[julia]
symbol = "î˜¤ "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

